include("src/Main.jl")
result = load_specimen_from_file!(joinpath(@__DIR__, "specimens", "comprehensive_v2_specimen.json"))
println("LOAD RESULT: $result")
println("Nodes loaded: ", length(NODE_MAP))
println("Lobes loaded: ", length(Lobe.LOBE_REGISTRY))
println("Bridges loaded: ", length(BRIDGE_MAP))
println("Sigils in table: ", length(_ENGINE_SIGIL_TABLE.entries))
println("Rules loaded: ", length(AIML_DROP_TABLE))
println("Thesaurus seeds: ", length(Thesaurus._THESAURUS_MAP))
println("Inhibitions: ", length(InputQueue._INHIBITION_SET))
println("AIML lobes: ", length(AIMLNodeSystem.get_registered_lobes()))
println("MLP rules: ", length(EphemeralMLP._MLP_RULES))
println("Automaton rules: ", length(EphemeralAutomaton._AUTOMATON_RULES))
println("Message history: ", length(_MESSAGE_HISTORY))
println("Coherence config weight: ", CoherenceField.COHERENCE_FIELD_CONFIG.weight)
println("Time orientation: ", _GLOBAL_TIME_ORIENTATION[])
println("Relational jitter enabled: ", RelationalJitter.is_jitter_enabled())
println("Answer modes: ", sort(collect(keys(_ANSWER_MODE_CONFIG))))
